baseURL: https://www.markus-nentwich.at/
languageCode: de-at
title: Markus Nentwich
theme: panna-cotta
enableRobotsTXT: true

params:
  core: https://core.markus-nentwich.at
  email: kontakt@markus-nentwich.at
  name: Markus Nentwich
  meta:
    title: Markus Nentwich
    description: Markus Nentwich (*28.12.1994) ist Musiker, Komponist und Arrangeur aus Niederösterreich. Auf dieser Homepage können Sie Noten kaufen und Workshops buchen.
    keywords:
      - Markus Nentwich
      - Eine letzte Runde
      - Viera Blech
      - Polka
      - Musik
      - Blasmusik
      - Noten
      - Posaune
      - Webshop
      - Verlag
    language: Deutsch
    topics:
      - Webshop
      - Noten
      - Musik
      - Person
      - Branche Produkt
      - Private Homepage
    audience:
      - Musiker
      - Musikverein
    revisit: 5
    robots: INDEX,FOLLOW
    authors:
      - Richard Stöckl
      - Dennis Toth
    publishers:
      - Richard Stöckl
      - Dennis Toth
  navbarlogo:
    # Logo (from static/images/logos/___)
    image: logos/nentwich.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Manage. Deploy.
    # Hero subtitle (optional)
    subtitle: Lorem ipsum sit dolor amet is dummy text used by the typography industry
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Noten
    data: categories
  - title: Kontakt
    url: /contact
  - title: Biografie
    url: /biografie
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: #nentwich.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://facebook.com/markus.nentwich.5
      # Icons are from Font Awesome
      icon: facebook
    - link: https://instagram.com/markus.nentwich
      icon: instagram
    - link: https://github.com/mknentwich
      icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Rechtliches"
        links:
        - text: Impressum
          link: /contact
        - text: AGB
          link: /agb
